export enum AppPermission {
  LOOKUP_GROUP_READ = 'LOOKUP_GROUP.READ',
  LOOKUP_GROUP_WRITE = 'LOOKUP_GROUP.WRITE',
  LOOKUP_GROUP_MANAGE = 'LOOKUP_GROUP.MANAGE',
  LOOKUP_VALUE_READ = 'LOOKUP_VALUE.READ',
  LOOKUP_VALUE_WRITE = 'LOOKUP_VALUE.WRITE',
  LOOKUP_VALUE_MANAGE = 'LOOKUP_VALUE.MANAGE',

  // Users
  USER_READ = 'USER.READ',
  USER_WRITE = 'USER.WRITE',
  USER_MANAGE = 'USER.MANAGE',

  ROLE_READ = 'ROLE.READ',
  ROLE_WRITE = 'ROLE.WRITE',
  ROLE_MANAGE = 'ROLE.MANAGE',

  CUSTOMER_READ = 'CUSTOMER.READ',
  CUSTOMER_WRITE = 'CUSTOMER.WRITE',
  CUSTOMER_MANAGE = 'CUSTOMER.MANAGE',
  PRODUCT_READ = 'PRODUCT.READ',
  PRODUCT_WRITE = 'PRODUCT.WRITE',
  PRODUCT_MANAGE = 'PRODUCT.MANAGE',

  // Orders
  ORDER_READ = 'ORDER.READ',
  ORDER_WRITE = 'ORDER.WRITE',
  ORDER_MANAGE = 'ORDER.MANAGE',

  REPORT_READ = 'REPORT.READ',
  REPORT_MANAGE = 'REPORT.MANAGE',
  BRAND_READ = 'BRAND.READ',
  BRAND_WRITE = 'BRAND.WRITE',
  BRAND_MANAGE = 'BRAND.MANAGE',
  CATEGORY_READ = 'CATEGORY.READ',
  CATEGORY_WRITE = 'CATEGORY.WRITE',
  CATEGORY_MANAGE = 'CATEGORY.MANAGE',
  UOM_READ = 'UOM.READ',
  UOM_WRITE = 'UOM.WRITE',
  UOM_MANAGE = 'UOM.MANAGE',
  UOM_CONVERSION_READ = 'UOM_CONVERSION.READ',
  UOM_CONVERSION_WRITE = 'UOM_CONVERSION.WRITE',
  UOM_CONVERSION_MANAGE = 'UOM_CONVERSION.MANAGE',
}
